### ISSUE TITLE
AttributeError: 'ElementReference' object has no attribute 'parent_chain' when using ElementReference as a parent to pom.Element

### ISSUE THREAD

**Issue by a-paleczny** [nickroeker/e2e.pom#2]
Here is a code snippet that generates the exception:

    foo_containers = pom.ElementCollection("Container Items").by_css(
        "[class*='Foo_Container-']"
    )

    def bar(self):
        for idx, baz in enumerate(self.foo_containers.find()):
            new_button = pom.Element(f"button[{idx}]", parent=baz).by_css(
                "[class*='some_button']"
            )
            new_button.click()     # exception occurs here

**Comment by nickroeker** [comment]
Imagine my confusion where a test specifically exists for this, but passed!

**The issue occurs only when `INFO` or above logging is enabled for `e2e.pom`**.

Until a fix is shipped, one can work around this simply by disabling logging on e2e.pom.

**Comment by nickroeker** [comment]
Should be fixed in `0.1.4`!
