### ISSUE TITLE
Remove or refactor Parentable._find_within abstract method

### ISSUE THREAD

**Issue by erwan-zimine-certn** [nickroeker/e2e.pom#3]
The _find_within abstract method is currently not adding too much value, not used anywhere in the base class and it obviously forces to override it.
mypy catches the issue when there is no override and display this error `Cannot instantiate abstract class XYZ with abstract attribute "_find_within"  [abstract]mypy(error)`. We can override the method but since it is not used in the base class, it seems an unnecessary step.

**Comment by nickroeker** [comment]
Should be fixed in version 0.1.8! Simply removed the method as it was no longer needed
